name = "Console-idated"
author = "S_N00B"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0b307421ed8323b31c8662dc8568c3e0fed8b7d52d1add6afa8434a637a8a4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
