name = "Console-idated"
author = "S_N00B"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f49927b44c948b77246e14b82dfbc7733b146429db87d7997b678dcf07a9156e"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
